### PR TITLE
38 read resources type

### PR DESCRIPTION
**Pull request by ojongerius**
This needs refactoring after #62 and #64

### CODE REVIEW

**Comment by ojongerius** [comment]
Some of these changes will make it to master, but need to be merged in to #62

**Comment by pmoust** [comment]
Any news on this?

**Comment by ojongerius** [comment]
Hi @pmoust, I'm currently tied up with other work, and had parked this one in favour of #64.

I'll have time to work on this one next week. Happy for you to raise a PR if you have the time, let me know if you are keen.

**Comment by ojongerius** [comment]
Declining the PR and will start work in a fresh branch in the next few days.

**Pull request closed without merging**
